// sprites/zombie.js — zombie / minion / boss pixel sprites (WO7 1.1 / 3.3, Agent A). Pure data,
// Node-safe (no DOM).
//
// Every sprite is an ASCII grid of PALETTE chars ('.' = transparent) parsed once at module load
// with pixel.parseGrid. Same conventions as soldier.js: all sprites face +x (right) at angle 0,
// +y is the zombie's RIGHT side, anchors are sprite-pixel CORNER coordinates, drawn at
// SPRITES.scale (2x). Sizes / anchors (contract, do not change):
//   normal: 16x16 body/legs/tearing/damaged/corpse, anchor (8, 8)   (radius 14 world px)
//   minion: 12x12 body/legs/corpse, anchor (6, 6)
//   boss:   40x40 body/charge/legs/corpse, anchor (20, 20)
//
// Layers (render order): legs (rotate to movement) -> body (rotate to target) -> damaged overlay
// (normal zombies below 50 % HP, same transform as the body).
//
// Normal body (WO7 FIX-4: each tier has its own silhouette AND palette; no olive 'G'/'g'/'L' so the
// soldier's olive uniform is the only green on screen). 1-px 'k' outline, head behind a 'k' ring.
//   walker   slumped: wide hunched back, head drooped low and less forward, ONE arm reaching
//            forward, the other dangling back along the side. Faded blue shirt 'C'/'K', bluish-grey
//            corpse skin 'M'/'m', grey face 'W'/'M', black eye sockets, dark-red mouth.
//   jogger   upright: compact torso, BOTH arms straight forward, torn brown jacket 'o'/'O'/'K' whose
//            tails flap out behind (ragged back edge), sickly yellow-ochre skin/face 'h'/'H', blood 'R'.
//   sprinter lean and forward-leaning: narrow torso, head pushed far forward, both arms swept BACK
//            like running. Near-black 'K'/'m' clothes, white face 'w'/'W', red eyes 'R', and a light
//            'W' rim on the top/back edge inside the outline so it reads on the dark BUNKER floor.
// Damaged overlay: 12 'R'/'r' pixels, each inside (never on the outline of) all 3 bodies and all 3
// tearing frames.
// Legs: 6-frame shamble, bare-toed shoes 'o' + 'S' toes, grey trousers 'm'/'K'. The left foot
// steps (planted foot moves back 3 px/frame = SPRITES.zombieStride 36 / 6 frames / scale 2),
// the right foot is dragged: smaller forward reach, shorter scuffing foot with a trailing 'K'.
//
// Boss tint marker: the crown/helmet region is painted with PALETTE 'p' (#b44dff). 'x' (magenta)
// is reserved for placeholders (isPlaceholder / tests flag it), so boss.tintColor is
// PALETTE.p, NOT '#ff00ff'. 'p' appears nowhere else in the boss sprites, so render can recolour
// exactly the pixels whose RGB equals tintColor (pixel.tint) to levelDef.boss.tint.
// See docs/notes/zombie-sprites.md.
import { parseGrid } from './pixel.js';
import { PALETTE } from './palette.js';

const WALKER = [
  '................',
  '....kkkkkkkkk...',
  '...kCCCMMMMMMkk.',
  '..kCCCKmmmmmmMWk',
  '.kCCCCKkkkkkkkk.',
  '.kCCCKkkkkk.....',
  'kCCCCkMMWWWk....',
  'kCKCCkmMWWkWk...',
  'kCCCCkmMMWWrk...',
  'kCKCCkmMMWWrk...',
  'kCCCCkmMMWkWk...',
  '.kCCCkkmMWWk....',
  '.kKCCKkkkkk.....',
  '.kmMKKKk........',
  '..kMmkk.........',
  '...kk...........',
];
const JOGGER = [
  '................',
  '...kkkkkkkkkkk..',
  '..kOOooooooHhhk.',
  '.kOoooKooKoHHhhk',
  'kOoookkkkkkkkkk.',
  '.kOookHHthhk....',
  'kOoRokHHhkhhk...',
  'kooRokHHhhrhk...',
  '.koRokHRhhrhk...',
  'kOoookHHhkRhk...',
  '.kOookHHhhhk....',
  'kOoookkkkkkkkkk.',
  '.kOoooKooKoHHhhk',
  '..kOOooooooHhhk.',
  '...kkkkkkkkkkk..',
  '................',
];
const SPRINTER = [
  '................',
  'kkk.............',
  'kWMkkkk.........',
  'kMmmmKKkk.......',
  '.kkkWWKKmk......',
  '...kWKKmkkkkkk..',
  '...kWKKmkWwwwRk.',
  '...kWKmmkWwwwwrk',
  '...kMKmmkMwwwwrk',
  '...kMKmmkMWwwRk.',
  '...kKKmmkkkkkk..',
  '.kkKKKmmk.......',
  'kMmmmKkk........',
  'kWMkkk..........',
  'kkk.............',
  '................',
];
const TEAR_WALKER = [
  '....kkkkk.......',
  '...kCCMMMkkkkk..',
  '...kCKmmmMMMMMk.',
  '..kCCCKKkmmmmkMk',
  '.kCCCCKkkkkkkkmk',
  '.kCCCKkkkkk..kk.',
  'kCCCCkMMWWWk....',
  'kCKCCkmMWWkWk...',
  'kCCCCkmMMWWrk...',
  'kCKCCkmMMWWrk...',
  'kCCCCkmMMWkWk...',
  '.kCCCkkmMWWk..k.',
  '.kKCCKkkkkkkkkMk',
  '..kKCKmmmmmmkMk.',
  '...kKmMMMMMMMk..',
  '....kkkkkkkkk...',
];
const TEAR_JOGGER = [
  '..kkkkkkkkkkkk..',
  '.kOOoooooooHhhkk',
  'kOooKooKooHHHkhk',
  'kOoookkkkkkkkkHk',
  'kOookkkkkkkkk.k.',
  '.kOookHHthhk....',
  'kOoRokHHhkhhk...',
  'kooRokHHhhrhk...',
  '.koRokHRhhrhk...',
  'kOoookHHhkRhk...',
  '.kOookHHhhhk....',
  'kOookkkkkkkkk.k.',
  'kOoookkkkkkkkkHk',
  'kOooKooKooHHHkhk',
  '.kOOoooooooHhhkk',
  '..kkkkkkkkkkkk..',
];
const TEAR_SPRINTER = [
  '...kkkkkkkkkk...',
  '..kWWMMMMMMMMkk.',
  '..kWKmmmmmmmkWk.',
  '..kKKkkkkkkkkMk.',
  '...kWWKKmk...k..',
  '...kWKKmkkkkkk..',
  '...kWKKmkWwwwRk.',
  '...kWKmmkWwwwwrk',
  '...kMKmmkMwwwwrk',
  '...kMKmmkMWwwRk.',
  '...kKKmmkkkkkk..',
  '...kKKKmmk...k..',
  '..kKKkkkkkkkkMk.',
  '..kWKmmmmmmmkWk.',
  '..kMMMMMMMMMMkk.',
  '...kkkkkkkkkk...',
];
const CORPSE_WALKER = [
  '............kMk.',
  '...........kMmk.',
  '.........kkMmk..',
  'kkk...kkkMmmk...',
  'oKKkkkCCMmkk....',
  'oKKKKCCCCCkkkk..',
  'kkkKCCCMCkkMWWk.',
  '...kCCCCCkmMWWWk',
  '...kCCCCCkMMWWWk',
  '...kCCCCKkMMMWrk',
  'kkkkKCCKKkkmMMk.',
  'oKKKKKKKKk.kkk..',
  'oKKKkkkMmkk.....',
  'kkkk...kMmmk....',
  '........kkMmk...',
  '..........kk....',
];
const CORPSE_JOGGER = [
  '............khk.',
  '...........khHk.',
  '.........kkhHk..',
  'kkk...kkkhHHk...',
  'ommkkkOOhHkk....',
  'oKKmmOOOookkkk..',
  'kkkKOOOhokkhhhk.',
  '...kOOoookohhhhk',
  '...kOooookhhhhhk',
  '...kooRoKkhhhhRk',
  'kkkkmooKrkkohhk.',
  'ommmKKKKKk.kkk..',
  'oKKKkkkhHkk.....',
  'kkkk...khHHk....',
  '........kkhHk...',
  '..........kk....',
];
const CORPSE_SPRINTER = [
  '............kWk.',
  '...........kWmk.',
  '.........kkWmk..',
  'kkk...kkkWmmk...',
  'ommkkkmmWmkk....',
  'oKKmmmmmKKkkkk..',
  'kkkKmmmWKkkwwwk.',
  '...kmmKKKkKwwwwk',
  '...kmKKKKkwWwwwk',
  '...kKKKKkkWWWwrk',
  'kkkkmKKkkkkKWWk.',
  'ommmKKkkkk.kkk..',
  'oKKKkkkWmkk.....',
  'kkkk...kWmmk....',
  '........kkWmk...',
  '..........kk....',
];
const DAMAGED = [
  '................',
  '................',
  '................',
  '...Rr...........',
  '................',
  '....r...........',
  '......R.........',
  '.......r.R......',
  '....R......r....',
  '......r.........',
  '.......R........',
  '................',
  '...rR...........',
  '................',
  '................',
  '................',
];
const LEGS0 = [
  '................',
  '................',
  '................',
  '.......kkkkkkk..',
  '......kmmmoooSk.',
  '......kKKKooook.',
  '.......kkkkkkk..',
  '................',
  '................',
  '..kkkkkk........',
  '.kSooommk.......',
  '.kooooKKk.......',
  '..kkkkkk........',
  '................',
  '................',
  '................',
];
const LEGS1 = [
  '................',
  '................',
  '................',
  '.......kkkk.....',
  '......koooSk....',
  '......kooook....',
  '.......kkkk.....',
  '................',
  '................',
  '....kkkk........',
  '...kSoomk.......',
  '..kKoooKk.......',
  '...kkkkk........',
  '................',
  '................',
  '................',
];
const LEGS2 = [
  '................',
  '................',
  '................',
  '....kkkk........',
  '...kSoook.......',
  '...kooook.......',
  '....kkkk........',
  '................',
  '................',
  '......kkkk......',
  '.....kmooSk.....',
  '.....kKoook.....',
  '......kkkk......',
  '................',
  '................',
  '................',
];
const LEGS3 = [
  '................',
  '................',
  '................',
  '..kkkkkk........',
  '.kSooommk.......',
  '.kooooKKk.......',
  '..kkkkkk........',
  '................',
  '................',
  '.......kkkkk....',
  '......kmmooSk...',
  '......kKKoook...',
  '.......kkkkk....',
  '................',
  '................',
  '................',
];
const LEGS4 = [
  '................',
  '................',
  '................',
  '.....kkkk.......',
  '....kSoook......',
  '....kooook......',
  '.....kkkk.......',
  '................',
  '................',
  '.......kkkkkk...',
  '......kmmmooSk..',
  '......kKKKoook..',
  '.......kkkkkk...',
  '................',
  '................',
  '................',
];
const LEGS5 = [
  '................',
  '................',
  '................',
  '.......kkkkk....',
  '......kmoooSk...',
  '......kKooook...',
  '.......kkkkk....',
  '................',
  '................',
  '......kkkk......',
  '.....koooSk.....',
  '.....kooook.....',
  '......kkkk......',
  '................',
  '................',
  '................',
];
const MINION = [
  '..........k.',
  '....kkkkkkWk',
  '...kKKKKKKWk',
  '..kpKKkkkkk.',
  '.kpKKkppKk..',
  '.kKpKkpKKRk.',
  '.kpKKkKKKRk.',
  '.kKKKkKKKk..',
  '..kKKKkkkkk.',
  '...kKKKKKKWk',
  '....kkkkkkWk',
  '..........k.',
];
const MINION_LEGS0 = [
  '............',
  '............',
  '............',
  '.....kkkk...',
  '....kKKKmk..',
  '.....kkkk...',
  '..kkkk......',
  '.kmKKKk.....',
  '..kkkk......',
  '............',
  '............',
  '............',
];
const MINION_LEGS1 = [
  '............',
  '............',
  '.....k......',
  '....kKk.....',
  '....kmk.....',
  '.....k......',
  '.....k......',
  '....kmk.....',
  '....kKk.....',
  '.....k......',
  '............',
  '............',
];
const MINION_LEGS2 = [
  '............',
  '............',
  '............',
  '..kkkk......',
  '.kmKKKk.....',
  '..kkkk......',
  '.....kkkk...',
  '....kKKKmk..',
  '.....kkkk...',
  '............',
  '............',
  '............',
];
const MINION_LEGS3 = [
  '............',
  '............',
  '.....k......',
  '....kKk.....',
  '....kmk.....',
  '.....k......',
  '.....k......',
  '....kmk.....',
  '....kKk.....',
  '.....k......',
  '............',
  '............',
];
const MINION_CORPSE = [
  '.k.......kk.',
  'kKk....kkKWk',
  '.kKkkkkKKkk.',
  '.kKkppKkk...',
  '..kKpKKkkk..',
  '..kpKKKKKKk.',
  '..kKKKKKKrk.',
  '..kKKKKpKk..',
  '..kKKKkkk...',
  '.kKkkkKKkkk.',
  'kKk...kkKKWk',
  '.k......kkk.',
];
const BOSS = [
  '........................................',
  '..................kkkkk.................',
  '.................kMMMMMk.kkkkk....kkkk..',
  '..............kkkMmmmmmkkMMMMMkkkkMmwWk.',
  '............kkMMMmmmmmmkkmmmmmMMMMMmkk..',
  '..........kkMMmmmmmmmmmkkmmmmmmmmmmKwWk.',
  '.........kMOMMmmmmKKKKKkkKKKKKmmmmmKkk..',
  '........kMMoMMKKKKmmmkk..kkkkkKKKKmKwWk.',
  '........kMMMoMMmmmmmmmk.......kkkkmKkk..',
  '.......kMMMMoMmmmmmmmKk...........kk....',
  '......kMMMMMommmmmmmKKmk................',
  '......kMMKMmmOmmmmmKKKmk................',
  '......kMMWMmmommmmrRKkmk................',
  '.....kMMMKMMmmommKKKkpkkkkk.............',
  '.....kMMMKMmmmoKKKKmmkpppppkkk..........',
  '.....kMMMWmmmmommmmkkkpppppkkWk.........',
  '.....kMMMKmmmmmOmmkpkppppppkkWWk........',
  '.....kMrmKmmmmmommmkppppWppkkkRWk.......',
  '.....kRMmWmmmmmommmkpppppppkkWWWk.......',
  '.....kMmmKmmmmmmomkkpppppppkkWWrwk......',
  '.....kmmmKmmmmmmokppKKKKKKpkkWWrwk......',
  '.....kmmmWmmmmmmOmkkpppppppkkWWWk.......',
  '.....kmmmKmmmmmmmoKkpppppppkkkRMk.......',
  '.....kmmmKmmmmmmmokpkpppWppkkMMk........',
  '.....kmmmWmmmmmmKoKkkkpppppkkMk.........',
  '.....kmmmKmmmMMMmmoKKkpppppkkk..........',
  '.....kmmmKmmMrRmmmOmkpkkkkk.............',
  '......kmmWmMMMrmmmmomkKk................',
  '......kmmKMMmmmmmmmomKKk................',
  '......kmmKMmmmmmmmmoKKKk................',
  '.......kmmmmmmmmmmKKoKk..........kkkk...',
  '........kmmmmmmmmKKKOKk......kkkkMmwWk..',
  '........kmKmmmMMMMKKokk.kkkkkMMMMMmkk...',
  '.........kKKmmmmmmMMMMMkMMMMMmmmmmKwWk..',
  '..........kkKmmmmmmmmmmkmmmmmmmmmmKkk...',
  '............kkKKKmmmmmmkmmmmmKKKKmKwWk..',
  '..............kkkKmmmmmkKKKKKkkkkmKkk...',
  '.................kKKKKKkkkkkk....kk.....',
  '..................kkkkk.................',
  '........................................',
];
const BOSS_CHARGE = [
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '............kkkkkkk.....................',
  '..........kkMMMMMMmk....................',
  '.........kMOMMMMMmmmkkkk............kkkk',
  '........kMMoMMMMmmMMMMMMk.kkkkkkkkkkMmwW',
  '........kMMMoMMMMMmmmmmmkkMMMMMMMMMMMmkk',
  '.......kMMMMoMmmmmmmmmmmkkmmmmmmmmmmmKwW',
  '......kMMMMMommmmmmmmmmmkkmmmmmmmmmmmKkk',
  '......kMMKMmmOKKKKKKKKKKkkKKKKKKKKKKmKwW',
  '......kMMWMmmommmmrRKmmk..kkkkkkkkkkmKkk',
  '.....kMMMKMMmmommKKKmmkpkkkkkkk.....kk..',
  '.....kMMMKMmmmoKKKKmmmmkpppppppk........',
  '.....kMMMWmmmmommmmmmkkkppppppppk.......',
  '.....kMMMKmmmmmOmmmmkpkpppppppppkk......',
  '.....kMrmKmmmmmommmmmkppppWpppppkWk.....',
  '.....kRMmWmmmmmommmmmkppppppppppkRk.....',
  '.....kMmmKmmmmmmommmkkppppppppppkWk.....',
  '.....kmmmKmmmmmmommkppKKKKKKKKKpkWk.....',
  '.....kmmmWmmmmmmOmmKkkppppppppppkRk.....',
  '.....kmmmKmmmmmmmoKKKkppppppppppkMk.....',
  '.....kmmmKmmmmmmmoKKkpkpppWpppppkk......',
  '.....kmmmWmmmmmmKoKKKkkkppppppppk.......',
  '.....kmmmKmmmMMMmmoKKKKkpppppppk........',
  '.....kmmmKmmMrRmmmOmKKkpkkkkkkk.....kkkk',
  '......kmmWmMMMrmmmMMMMMk..kkkkkkkkkkMmwW',
  '......kmmKMMmmMMMMmmmmmmkkMMMMMMMMMMMmkk',
  '......kmmKMmmmmmmmmmmmmmkkmmmmmmmmmmmKwW',
  '.......kmmmmmmmmmmmmmmmmkkmmmmmmmmmmmKkk',
  '........kmmmmmKKKKKKKKKKkkKKKKKKKKKKmKwW',
  '........kmKmmmmmKKKKokkk..kkkkkkkkkkmKkk',
  '.........kKKmmmKKKKKkok.............kk..',
  '..........kkKmKKKKKkkok.................',
  '............kkkkkkk..k..................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
];
const BOSS_LEGS0 = [
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '......................kkkkkkkkkk........',
  '................kkkkkkKKKKKKKKKwk.......',
  '...............kOOOOOOKMMMMMMMKk........',
  '...............kOOOOOOKmmmmmmmKwk.......',
  '...............kooooooKmmmmmmmKk........',
  '...............kooooooKmmmmmmmKwk.......',
  '...............kooooooKmmmmmmmKk........',
  '...............kooooooKKKKKKKKKwk.......',
  '................kkkkkkKKKKKKKKKk........',
  '......................kkkkkkkkk.........',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '......kkkkkkkkkk........................',
  '.....kKKKKKKKKKwk.......................',
  '.....kKMMMMMMMKOOk......................',
  '.....kKmmmmmmmKwOk......................',
  '.....kKmmmmmmmKook......................',
  '.....kKmmmmmmmKwok......................',
  '.....kKmmmmmmmKook......................',
  '.....kKKKKKKKKKwok......................',
  '.....kKKKKKKKKKkk.......................',
  '......kkkkkkkkk.........................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
];
const BOSS_LEGS1 = [
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '..............kkkkkkkkkk................',
  '.............kKKKKKKKKKwk...............',
  '.............kKMMMMMMMKk................',
  '.............kKmmmmmmmKwk...............',
  '.............kKmmmmmmmKk................',
  '.............kKmmmmmmmKwk...............',
  '.............kKmmmmmmmKk................',
  '.............kKKKKKKKKKwk...............',
  '.............kKKKKKKKKKk................',
  '..............kkkkkkkkk.................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '..............kkkkkkkkkk................',
  '.............kKKKKKKKKKwk...............',
  '.............kKMMMMMMMKk................',
  '.............kKmmmmmmmKwk...............',
  '.............kKmmmmmmmKk................',
  '.............kKmmmmmmmKwk...............',
  '.............kKmmmmmmmKk................',
  '.............kKKKKKKKKKwk...............',
  '.............kKKKKKKKKKk................',
  '..............kkkkkkkkk.................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
];
const BOSS_LEGS2 = [
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '......kkkkkkkkkk........................',
  '.....kKKKKKKKKKwk.......................',
  '.....kKMMMMMMMKOOk......................',
  '.....kKmmmmmmmKwOk......................',
  '.....kKmmmmmmmKook......................',
  '.....kKmmmmmmmKwok......................',
  '.....kKmmmmmmmKook......................',
  '.....kKKKKKKKKKwok......................',
  '.....kKKKKKKKKKkk.......................',
  '......kkkkkkkkk.........................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '......................kkkkkkkkkk........',
  '................kkkkkkKKKKKKKKKwk.......',
  '...............kOOOOOOKMMMMMMMKk........',
  '...............kOOOOOOKmmmmmmmKwk.......',
  '...............kooooooKmmmmmmmKk........',
  '...............kooooooKmmmmmmmKwk.......',
  '...............kooooooKmmmmmmmKk........',
  '...............kooooooKKKKKKKKKwk.......',
  '................kkkkkkKKKKKKKKKk........',
  '......................kkkkkkkkk.........',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
];
const BOSS_LEGS3 = [
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '..............kkkkkkkkkk................',
  '.............kKKKKKKKKKwk...............',
  '.............kKMMMMMMMKk................',
  '.............kKmmmmmmmKwk...............',
  '.............kKmmmmmmmKk................',
  '.............kKmmmmmmmKwk...............',
  '.............kKmmmmmmmKk................',
  '.............kKKKKKKKKKwk...............',
  '.............kKKKKKKKKKk................',
  '..............kkkkkkkkk.................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '..............kkkkkkkkkk................',
  '.............kKKKKKKKKKwk...............',
  '.............kKMMMMMMMKk................',
  '.............kKmmmmmmmKwk...............',
  '.............kKmmmmmmmKk................',
  '.............kKmmmmmmmKwk...............',
  '.............kKmmmmmmmKk................',
  '.............kKKKKKKKKKwk...............',
  '.............kKKKKKKKKKk................',
  '..............kkkkkkkkk.................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
];
const BOSS_CORPSE = [
  '...............................k........',
  '..............................kwk.......',
  '............................kkMk........',
  '...........................kMMmwk.......',
  '..........................kMmmmk........',
  '........................kkMmmmmwk.......',
  '.......................kMMmmmmkk........',
  'kkkk.................kkMmmmmkk..........',
  'mmmmk..........kkkkkkMMmmmmk............',
  'mmmmkk.......kkMMMMMMmmmmmk.............',
  'mmmmookkk...koMMMMMMmmmmkk..............',
  'mmmmoooookk.kMoMMMMMmmmmmk..............',
  'mmmmoooooookMMoMMMMmmmmmmmk.............',
  'mmmmooooooooMMMoMMmmmmmmmmk.............',
  'mmmmoooooooMMMMommmmmmmmmmmk.kk.........',
  'kkkkkkoooooMMMMmommmmmmmmmmkkMMkk.......',
  '......kkkoMMMMmmmommmmmmmmmMMMMMMk......',
  '.........kMMMmmmmommmmmmmmMMMMMMMMk.....',
  '.........kMMmmmmrRommmmmmKMMMMMMkMk.....',
  '.........kMmmmmmmrommmmmKMMMMMMMMMMk....',
  '.........kmmmmmmmmmommmKKMMMMMMMMMrk....',
  '.........kmmmmmmmmmmomKKKKmmmmmmmmk.....',
  '.........kmmmmmmmmmmoKKKKKmmmmmmkmk.....',
  '.........kmmmmmmmmmmKoRKKKKmmmmmmk......',
  '......kkkoommmmmmmmKKoKKKKKkkmmkk.......',
  'kkkkkkooooommmmmmmKKKKoKKKKk.kk.........',
  'mmmmoooooooommmmmKKKKKKoKKk.............',
  'mmmmoooooooommmmKKKKKKKoKKk.............',
  'mmmmoooooookkmmKKKmKKKKKok.......kkkkk..',
  'mmmmoooookk..kKKKKmmKKKKok......kpppppk.',
  'mmmmookkk.....kKKKmmmmKkkok....kpppppppk',
  'mmmmkk.........kkkKmmmmk.k.....kpkpppppk',
  'mmmmk.............kKmmmmkk.....kpkpppppk',
  'kkkk...............kKKmmmmk....kpkpppppk',
  '....................kkKmmmmk....kpppppk.',
  '......................kKmmmk.....kkkkk..',
  '.......................kKKmkk...........',
  '........................kkKkwk..........',
  '..........................kwk...........',
  '...........................k............',
];

const P = (g) => parseGrid(g);

const TEARING_V = { walker: P(TEAR_WALKER), jogger: P(TEAR_JOGGER), sprinter: P(TEAR_SPRINTER) };
const CORPSE_V = { walker: P(CORPSE_WALKER), jogger: P(CORPSE_JOGGER), sprinter: P(CORPSE_SPRINTER) };

export const ZOMBIE_SPRITES = {
  normal: {
    body: { walker: P(WALKER), jogger: P(JOGGER), sprinter: P(SPRINTER) },
    legs: { frames: [LEGS0, LEGS1, LEGS2, LEGS3, LEGS4, LEGS5].map(P), anchor: { x: 8, y: 8 } },
    tearing: TEARING_V.walker,   // arms raised forward, clawing (walker palette)
    damaged: P(DAMAGED),         // blood overlay drawn over the body below 50 % HP
    corpse: CORPSE_V.walker,
    anchor: { x: 8, y: 8 },
    // Extras (not in 3.3): per-tier tearing / corpse, so tiers keep their colours.
    tearingVariants: TEARING_V,
    corpseVariants: CORPSE_V,
  },
  minion: {
    body: P(MINION),
    legs: { frames: [MINION_LEGS0, MINION_LEGS1, MINION_LEGS2, MINION_LEGS3].map(P), anchor: { x: 6, y: 6 } },
    corpse: P(MINION_CORPSE),
    anchor: { x: 6, y: 6 },
  },
  boss: {
    body: P(BOSS),
    charge: P(BOSS_CHARGE),        // arms thrust forward, head lowered
    legs: { frames: [BOSS_LEGS0, BOSS_LEGS1, BOSS_LEGS2, BOSS_LEGS3].map(P), anchor: { x: 20, y: 20 } },
    corpse: P(BOSS_CORPSE),
    anchor: { x: 20, y: 20 },
    tintColor: PALETTE.p,          // marker colour ('p') of the crown/helmet pixels
    tintChar: 'p',
  },
};

// zombie.js tier names -> normal body variant.
const TIER_VARIANT = { walk: 'walker', jog: 'jogger', sprint: 'sprinter' };

// -> { body, legs, corpse, anchor, tearing } for z.kind ('normal' | 'minion' | 'boss') and
// z.tier. Unknown kinds fall back to 'normal'; unknown tiers to 'walker'. For normal zombies
// corpse / tearing are the tier's own colours; minion and boss have no tearing frame (null).
export function zombieSpriteFor(z) {
  const kind = z && z.kind;
  if (kind === 'boss') {
    const b = ZOMBIE_SPRITES.boss;
    return { body: b.body, legs: b.legs, corpse: b.corpse, anchor: b.anchor, tearing: null };
  }
  if (kind === 'minion') {
    const m = ZOMBIE_SPRITES.minion;
    return { body: m.body, legs: m.legs, corpse: m.corpse, anchor: m.anchor, tearing: null };
  }
  const n = ZOMBIE_SPRITES.normal;
  const variant = TIER_VARIANT[z && z.tier] || 'walker';
  return { body: n.body[variant], legs: n.legs, corpse: n.corpseVariants[variant], anchor: n.anchor, tearing: n.tearingVariants[variant] };
}
